### ISSUE TITLE
Permission Dialog Dismissal During Navigation in Android 13

### ISSUE THREAD

**Issue by ali-thowfeek** [Kumulos/KumulosSdkAndroid#95]
# Description:

When calling `pushRequestDeviceToken` in the application class as recommended in the Kumulos documentation, a permission dialog is triggered for devices running Android 13. However, the presence of a subsequent startActivity(intent) call in my launcher activity causes the permission dialog to be dismissed.

# Proposed Solution:

A potential solution to this issue is to introduce a callback mechanism for the pushRequestDeviceToken method. This callback would allow us to determine whether the user has taken action on the permission dialog before proceeding with further app navigations. By having this callback, we can ensure that the permission dialog is not inadvertently dismissed.

Kumulos SDK Version: 15.0.1
Android emulator API 33

**Comment by cgwyllie** [comment]
Hi @ali-thowfeek , thanks for the feedback, we'll pass it to our product team.

Provided you target the latest API level, the system won't show the permission request until you call the SDK API.

If desired you can move the `pushRequestDeviceToken` call to your main activity (or wherever makes sense) if you detect you are running on Android 13+ so the permission request is not dismissed by the `startActivity` call.

If there's anything else, please feel free to re-open or email us on support@kumulos.com.
